line-length    = 88
target-version = "py310"


[lint]
    exclude = ["examples"]

    explicit-preview-rules = false
    ignore = [
        "incorrect-blank-line-before-class",
        "multi-line-summary-second-line",
        "runtime-cast-value",
        "import-private-name",
        "missing-copyright-notice",
        "missing-trailing-comma",
    ]
    preview = true
    select = ["ALL"]


    [lint.per-file-ignores]
        "examples/*" = ["implicit-namespace-package"]
        "examples/test_target.py" = ["undefined-name"]
        "scripts/*.py" = ["assert", "print", "implicit-namespace-package"]
        "src/debug_dojo/_cli.py" = ["typing-only-standard-library-import"]
        "src/debug_dojo/_installers.py" = [
            "import-outside-top-level",
            "debugger",
        ]
        "tests/*" = ["assert", "print", "docstring-missing-returns", "PT"]
        "tests/assets/*" = ["print", "implicit-namespace-package", "undefined-name"]

[format]
    docstring-code-format = true
